### ISSUE TITLE
Error when instantiating the [fluid~] object

### ISSUE THREAD

**Issue by ofefo** [porres/pd-fluid#1]
Pd version 0.51.0

After following the installation steps, I get the following error when trying to put a [fluid~]  object:
```
[fluid~] for Pd, using fluidsynth version: 2.2.0
 This is a test version, unreleased
 The code's repository is https://github.com/porres/pd-fluid
-- initializing [fluid~] for Pd --
-- [fluid~] loaded --
(Tcl) UNHANDLED ERROR: bad screen distance "97,000000"
    while executing
"$tkcanvas create text $x $y -tags $tags  -text [::pdtk_text::unescape $text]  -fill $color -anchor nw -font [get_font_for_size $font_size]"
    (procedure "pdtk_text_new" line 2)
    invoked from within
"pdtk_text_new .x561028a25770.c {.x561028a25770.t561028c92340 obj text} 97,000000 92,000000 {fluid~ } 12 black"
    ("uplevel" body line 31)
    invoked from within
"uplevel #0 $docmds"
```

The object appears onscreen with no text, and then I'm unable to load any other vanilla objects.
![fluid](https://user-images.githubusercontent.com/34070888/115125314-a9a86780-9f9d-11eb-9e97-a55b23948f9d.png)

**Comment by porres** [comment]
weird, you need to give more details on your system, but I'm afraid I'm not that good with that

**Comment by ofefo** [comment]
I'm on Ubuntu 20.04 and fluidsynth was installed from source.
When running Pd from terminal and trying to instantiate [fluid~], I also receive the following on terminal:

```
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
fluidsynth: error: Unknown numeric setting 'synth.midi-channels'
fluidsynth: error: Unknown numeric setting 'synth.polyphony'
fluidsynth: error: Unknown string setting 'synth.chorus.active'
fluidsynth: error: Unknown string setting 'synth.reverb.active'
fluidsynth: error: Unknown string setting 'synth.ladspa.active'
```

some more information from Pd startup:

```
Tk 8.6.10
detected font: DejaVu Sans Mono
using font: DejaVu Sans Mono bold
Loading plugin: /usr/local/lib/pd/tcl/pd_deken.tcl
[deken]: platform detected: Linux-x86_64-float32
Loading plugin: /usr/local/lib/pd/tcl/pd_docsdir.tcl
[deken]: platform re-detected: Linux-amd64-float32
```

The same error happens when running as root.

**Comment by porres** [comment]
yeah, I have 0 knowledge on linux, but if you wait, I'll soon include this in my ELSE library and support for all OSes

**Comment by porres** [comment]
weird thing is that there's no tcl/tk involved here

**Comment by ofefo** [comment]
> yeah, I have 0 knowledge on linux, but if you wait, I'll soon include this in my ELSE library and support for all OSes

That would be awesome! I was wondering why you didn't uploaded it directly to deken.

**Comment by porres** [comment]
I'm not done with this yet... it is unreleased as it says ;)

**Comment by porres** [comment]
oh, actually... this won't be released!!!

sorry for the confusion, I thought you were filing an issue here: https://github.com/porres/pd-fluidsynth

forget about this repository, I'm disowning it :)

**Comment by ofefo** [comment]
oh ok. I'm gonna try the other one again.
